<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:29:30
sfConfig::add(array(
  'mod_ticketscomments_enabled' => true,
  'mod_ticketscomments_view_class' => 'sfPHP',
));
