<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:22:37
sfConfig::add(array(
  'mod_ticketsreports_enabled' => true,
  'mod_ticketsreports_view_class' => 'sfPHP',
));
