<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:15:47
sfConfig::add(array(
  'mod_projectsphases_enabled' => true,
  'mod_projectsphases_view_class' => 'sfPHP',
));
