<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:22:41
sfConfig::add(array(
  'mod_projectsreports_enabled' => true,
  'mod_projectsreports_view_class' => 'sfPHP',
));
