<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 15:55:16
sfConfig::add(array(
  'mod_projectsstatus_enabled' => true,
  'mod_projectsstatus_view_class' => 'sfPHP',
));
