<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:00:10
sfConfig::add(array(
  'mod_versionsstatus_enabled' => true,
  'mod_versionsstatus_view_class' => 'sfPHP',
));
