<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:48:41
sfConfig::add(array(
  'mod_accessforbidden_enabled' => true,
  'mod_accessforbidden_view_class' => 'sfPHP',
));
