<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2019/01/13 16:06:04
sfConfig::add(array(
  'mod_projectscomments_enabled' => true,
  'mod_projectscomments_view_class' => 'sfPHP',
));
